### ISSUE TITLE
How do I change "Click me" Button to custom name ?

### ISSUE THREAD

**Issue by giangdip2410** [streamlit/component-template#17]
Thank you for great feature. It is help me a lots but I want to change the display name of click button . Do you know how to change it .
Thank you.

**Comment by randyzwitch** [comment]
Hi @giangdip2410 - 

Which function are you referring to?

Best,
Randy

**Comment by giangdip2410** [comment]
@randyzwitch : thank you for your reply. I use function button. I was able to changed Button Click me as custom name.

**Comment by vdonato** [comment]
Closing as this seems to have been resolved. Feel free to let me know if there's something else that needs to be done here.
