### ISSUE TITLE
Add children to a custom component

### ISSUE THREAD

**Issue by MehdiChelh** [streamlit/component-template#20]
Hello,
First thank you for this amazing project 👍 !
I tried to create a custom component with the ability to add children to the component (text, map, bar_chart...), similar to what can be done using `st.columns`

What I would like to do for example with this component, is something like:
```python
el1, el2 = my_component(2)
el1.write("this is in element 1")
el2.bar_chart(hist_values)
```

- Is it possible using `component-template` ? Or should it be done in some way with streamlit's `DeltaGenerator` class or something similar ?

I am quite new to streamlit, so I don't really know where to start and if it is even possible.

Thanks!

**Comment by sfc-gh-kbregula** [comment]
Thanks for sharing this question! We use GitHub Issues for bugs that impact the templates; since this error is specific to your user case and your development of component, do you mind sharing it in [our forum](https://discuss.streamlit.io/) instead?
