### ISSUE TITLE
Include tests

### ISSUE THREAD

**Issue by Industrial** [streamlit/component-template#22]
Hi.

The component template does not include tests. Please add one to verify that running tests works (it doesn't).

Running tests I get errors here:

```
node_modules/streamlit-component-lib/dist/index.js:17
    export { StreamlitComponentBase, withStreamlitConnection } from "./StreamlitReact";
    ^^^^^^

    SyntaxError: Unexpected token 'export'
```

Using `ts-node`.

**Comment by sfc-gh-kbregula** [comment]
We added tests to CI that check if the project builds in the latest versions of NodeJS. We have also started working on adding E2E tests to add even more confidence in our templates.
