### ISSUE TITLE
Update react-scripts to 5.0.0

### ISSUE THREAD

**Issue by Industrial** [streamlit/component-template#23]
Hi. You are currently using React Scripts 4.x.x. This is an old version.

When I update it to 5.x.x I get compile/type errors for Apache Arrow.

Please update `react-scripts` to `5.0.0`.

**Comment by PvanHengel** [comment]
Any update on this I see the same issue when trying to use the latest version of react.  Ive also updated to v 1.4.0 of the library, still no dice...


ERROR in ./node_modules/streamlit-component-lib/dist/ArrowTable.js 83:13-27
export 'Type' (imported as 'Type') was not found in 'apache-arrow' (module has no exports)

ERROR in ./node_modules/streamlit-component-lib/dist/ArrowTable.js 95:21-31
export 'Table' (imported as 'Table') was not found in 'apache-arrow' (module has no exports)

ERROR in ./node_modules/streamlit-component-lib/dist/ArrowTable.js 96:22-32
export 'Table' (imported as 'Table') was not found in 'apache-arrow' (module has no exports)

ERROR in ./node_modules/streamlit-component-lib/dist/ArrowTable.js 97:24-34
export 'Table' (imported as 'Table') was not found in 'apache-arrow' (module has no exports)

ERROR in ./node_modules/streamlit-component-lib/dist/ArrowTable.js 100:26-36
export 'Table' (imported as 'Table') was not found in 'apache-arrow' (module has no exports)

**Comment by changsin** [comment]
+1

**Comment by sfc-gh-kbregula** [comment]
We released a new version of Streamlit Component Library v2.0 that addresses this issue
Npm registry: https://www.npmjs.com/package/streamlit-component-lib
Release notes: https://github.com/streamlit/streamlit/blob/develop/component-lib/RELEASE_NOTES.md
