### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by Ralghs** [streamlit/component-template#31]
I got this error after running "npm install"

`npm WARN deprecated fsevents@1.2.4: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

up to date, audited 1825 packages in 23s

92 packages are looking for funding
  run `npm fund` for details

80 vulnerabilities (13 low, 18 moderate, 45 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.`

I looked online and couldn't find much information regarding this error. Does anybody know why?

**Comment by Ralghs** [comment]
I ignored this problem and proceed to "npm start". I ran "npm start" and "streamlit run ....", I got 

Your app is having trouble loading the init.my_component component.

(The app is attempting to load the component from http://localhost:3001/, and hasn't received its "streamlit
" message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?
For more troubleshooting help, please see the [Streamlit Component docs](https://docs.streamlit.io/library/components) or visit our [forums](https://discuss.streamlit.io/).

**Comment by Ellepourmoi** [comment]
This is the message "opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'"  what can be done to overcome this.Please help

**Comment by sfc-gh-kbregula** [comment]
We have updated all dependencies and released a new version of the library which should solve this problem.
Npm registry: https://www.npmjs.com/package/streamlit-component-lib
Release notes: https://github.com/streamlit/streamlit/blob/develop/component-lib/RELEASE_NOTES.md

> code: 'ERR_OSSL_EVP_UNSUPPORTED'" 

This error occurred if you were using too new NodeJS relative to the installed version of react-script. We now use react-script v5 and we support the following NodeJS versions: `16.x`, `18.x`, `19.x`.
