### ISSUE TITLE
Component not visible in Streamlit component gallery

### ISSUE THREAD

**Issue by Vishnu-Moorthi** [streamlit/component-template#54]
We have published the component on July 07, 2023. Still now not reflected on Streamlit component library.

Name of the component: EJ2-Streamlit-Grid
Github URL: https://github.com/SyncfusionExamples/Getting-started-with-Syncfusion-Grid-component-in-Streamlit-app
PyPI package: https://pypi.org/project/ej2-streamlit-grids/

**Comment by sfc-gh-kbregula** [comment]
@carolinedlu  Do you know what the process of publishing a component in the gallery looks like?

**Comment by carolinedlu** [comment]
@sfc-gh-kbregula @Vishnu-Moorthi This component has been added to our gallery. Thanks!

**Comment by sfc-gh-kbregula** [comment]
I found documentation on how to promote the component you created.
https://docs.streamlit.io/library/components/publish#promote-your-component
We then review the components that are popular on the forum and publish them in our gallery.
