### ISSUE TITLE
Quick Start Guide Not Working

### ISSUE THREAD

**Issue by Commando-Brando** [streamlit/component-template#74]
Hey guys followed the quick start guide step by step.

In one terminal I did `npm i` & `npm run start`
In another I created virtual env, activated it, and then ran streamlit using  `streamlit run my_component/example.py`

I am getting the following error when after going to `localhost:8501`

```
File "C:\Users\...\code\test-st-template\my_component\example.py", line 2, 
in <module>
    from my_component import my_component
ModuleNotFoundError: No module named 'my_component'
```

Am I doing something wrong or is it out of date?

**Comment by hagemon** [comment]
I met the same problem, A temporary solution is to add
```python
import os
import sys
sys.path.insert(0, os.path.abspath('..'))
```
before
```python
from my_component import my_component
```
in `example.py`.

Maybe there is a better way to solve the problem, but this works for me at the moment.

**Comment by SeemaJehan** [comment]
Thanks! Alternatively place the example.py file outside my_component and then run streamlit using `streamlit run example.py`

**Comment by sfc-gh-pbelczyk** [comment]
Hi,
Thanks for the ticket.
We have updated our documentation to include the installation of the template as an editable package needed to run the example.

**Comment by alexanderchr** [comment]
Still does not work. Had to change

https://github.com/streamlit/component-template/blob/master/template/setup.py#L9

```name="my-component"```
