### ISSUE TITLE
Missing script: "export"

### ISSUE THREAD

**Issue by oparisy** [streamlit/component-template#94]
Hi, when trying to apply the [Prepare your Component](https://docs.streamlit.io/develop/concepts/custom-components/publish#prepare-your-component) step of [Publish to PyPi](https://docs.streamlit.io/develop/concepts/custom-components/publish), I get the following error:
```sh
$ npm run export
npm ERR! Missing script: "export"
```

But if I do `npm run build`, I get the `frontend/build/` folder properly created, and then when setting `_RELEASE = True` I can then use the component without starting the Webpack dev server, as expected.

Is my npm install too old (9.5.1, but note that [ Development Environment Setup](https://docs.streamlit.io/develop/concepts/custom-components/intro#development-environment-setup) does not specify a minimum version)? Or is the documentation to be updated?

Regards,
Olivier.

**Comment by raethlein** [comment]
Hey @oparisy thanks for opening the issue and sorry for the delayed reply! We have updated the docs in context of this issue https://github.com/streamlit/docs/pull/1031. Hence, I am going to close this one here, too!
